### ISSUE TITLE
The format of the URI could not be determined.

### ISSUE THREAD

**Issue by MortenHoustonLudvigsen** [MortenHoustonLudvigsen/KarmaTestAdapter#13]
In some cases an error 'The format of the URI could not be determined.' is thrown when getting a relative path.

**Comment by MortenHoustonLudvigsen** [comment]
I have not been able to reproduce this problem, but I have simplified the method in question, and I think this issue is resolved.
A prerelease can be downloaded here: <https://github.com/MortenHoustonLudvigsen/KarmaTestAdapter/releases/download/v1.0.1-issue-13/KarmaTestAdapter.vsix>

@cResults Would you be able to test?

**Comment by cResults** [comment]
Sure.   I’ll let you know what I find.

**Comment by cResults** [comment]
After running the KarmaTestAdapter.vsix I get:
[cid:image001.png@01D05DA2.A0E9B3E0]

**Comment by MortenHoustonLudvigsen** [comment]
@cResults I couldn't see you image, but I just realized that I forgot to bump the version. I have just done that. If you download the vsix file again, it should be possible to install.

**Comment by cResults** [comment]
Version was the issue.  I have it installed.
```
[karma] [Projects\Source\Web\ui] Creating KarmaTestContainer for Projects\Source\Web\ui\KarmaTestAdapter.json
[karma] [Projects\Source\Web\ui] Watching Projects\Source\Web\ui\KarmaTestAdapter.json
[karma] [Warning] [Projects\Source\Web\ui] Karma configuration file not found: karma.conf.src.js
------ Discover test started ------
========== Discover test finished: 810 found (0:00:06.6055748) ==========

```
Karma.conf.src.js  is located in the same directory as KarmaTestAdapter.json

**Comment by MortenHoustonLudvigsen** [comment]
@cResults Thanks! Sounds like this issue is resolved?

The adapter requires that configuration files (`KarmaTestAdapter.json` and in this case `karma.conf.src.js`) are included in the Visual Studio project. Is this the case?

**Comment by cResults** [comment]
Yes, they appear to be.
![image](https://cloud.githubusercontent.com/assets/5702582/6646123/6aea586e-c998-11e4-807d-81b8408ccb3b.png)

**Comment by cResults** [comment]
I unloaded the project and confirmed that both are included.

**Comment by MortenHoustonLudvigsen** [comment]
I'll close this issue, and continue with #15.
