### ISSUE TITLE
Concatenate a test's suites in front of the test description

### ISSUE THREAD

**Issue by cResults** [MortenHoustonLudvigsen/KarmaTestAdapter#24]
One of the beauties of jasmine is the ability to have an easily readable test output that describes the behavior of a module. Right now only the text for the 'it' function is displayed in Test Explorer.  The suites for a given test are not display. 

![image](https://cloud.githubusercontent.com/assets/5702582/6695950/b134b578-ccbb-11e4-8f6c-4d345fc73aa9.png)
 
If I just broke a test that someone else wrote or one I wrote a year ago, I have no idea what "should be retained" (see image above).  But if the suites are concatenated in front of the 'it' description, I will know what it is that "should be retained".  

Keep in mind that suites can be nested, so it will be necessary to loop through the array of suites that already exists in the test object that is displayed in the log files.

If there are people who only want the "it" description, it could be a config setting that determines the behavior.

This is a nice to have, not a need to have.

Thank you for a great product.

**Comment by MortenHoustonLudvigsen** [comment]
@cResults

I agree with your points, so I have change the default accordingly. However, others might want different generation of display names. So I have made it configurable.

See [Release v1.0.4-alpha1](https://github.com/MortenHoustonLudvigsen/KarmaTestAdapter/releases/tag/v1.0.4-alpha1)

If you have the time and inclination, I would very much appreciate it if you would take it for a spin. :smile:

**Comment by MortenHoustonLudvigsen** [comment]
Please see [Release v1.0.4-alpha2](https://github.com/MortenHoustonLudvigsen/KarmaTestAdapter/releases/tag/v1.0.4-alpha2) instead.

**Comment by cResults** [comment]
This is working great.  Thank you.

**Comment by MortenHoustonLudvigsen** [comment]
Great! I'll close this issue then.
