### ISSUE TITLE
configure test entries so that they behave as expected in Test Explorer's grouping and sorting

### ISSUE THREAD

**Issue by cResults** [MortenHoustonLudvigsen/KarmaTestAdapter#25]
In Test Explorer you can group/sort tests by:
* Class
* Duration
* Outcome
* Traits
* Project

These can be set via the control highlighted in yellow in the image below.

![image](https://cloud.githubusercontent.com/assets/5702582/6696155/88afe8d2-ccbd-11e4-8733-f9545f230097.png)

I would like to request that all test be marked with a Trait of JavaScript.  This allows teams that have a Visual Studio solution with both C# and JavaScript tests to easily group all of the JavaScript tests.

Second, I would recommend setting the Class as the outer most suite which is set in the out most describe function in jasmine.  I'm certain there are exceptions somewhere, but every test I've seen, the outer most describe function states the name of the module that is being tested.  Right now this sorts on the "it" function's description as seen below.

![image](https://cloud.githubusercontent.com/assets/5702582/6696443/d0d49656-ccbf-11e4-9c88-60509a1962e3.png)

These would be nice to haves. 

Thank you for a great product.

**Comment by MortenHoustonLudvigsen** [comment]
This issue should be resolved in the latest prerelease.

See [Release v1.0.4-alpha1](https://github.com/MortenHoustonLudvigsen/KarmaTestAdapter/releases/tag/v1.0.4-alpha1)

**Comment by MortenHoustonLudvigsen** [comment]
Please see [Release v1.0.4-alpha2](https://github.com/MortenHoustonLudvigsen/KarmaTestAdapter/releases/tag/v1.0.4-alpha2) instead.

**Comment by cResults** [comment]
This all is working Great.

Here's an example of sort/group by Trait:
![image](https://cloud.githubusercontent.com/assets/5702582/6786583/ae67133e-d163-11e4-8a21-1a1f61c01d34.png)

The green squiggle under the Traits property of KarmaTestAdapter.json is complaining that Traits isn't valid for the json schema.

Here's an example of using the sort/group by Class:
![image](https://cloud.githubusercontent.com/assets/5702582/6786697/4b3383aa-d164-11e4-8264-a7bc95cb65d3.png)

I used to add "js~ " to the beginning of each jasmine suite in order to have a means of separating JavaScript tests from C# tests in Test Explorer. Having the functionality provided in this issue, I will no longer need to to that.

Thank you for the improved helpful functionality.

**Comment by MortenHoustonLudvigsen** [comment]
Great! I'll have a look at the schema tomorrow.

**Comment by MortenHoustonLudvigsen** [comment]
@cResults I have checked the schema, and it should work. At least it does for me :smile: 
I have made a small change, to require the `Name` property for traits specified with name and value.
I'll go ahead and close this issue. If you have further trouble with the schema, please open a new issue.
Once again, thanks for all your input!
