### ISSUE TITLE
Unable to jump to a failed test when using the PhantomJS runner.

### ISSUE THREAD

**Issue by zacharybussey** [MortenHoustonLudvigsen/KarmaTestAdapter#27]
I'm able to run jasmine tests using the PhantomJS browser.  But, when a test fails, I'm unable to click on the failed test and jump to failing test.  However, when running the same tests in Chrome, this behavior works properly.

There is a message that shows in the status bar, at the bottom of Visual Studio, which reads "Cannot open the following file: C:/path/to/project/node_modules/jasmine-core/lib/jasmine.js"

**Comment by MortenHoustonLudvigsen** [comment]
@zacharybussey I have a number of test projects in the `TestProjects` folder of this repository. Most of them use PhantomJS, and I have a test suite, that verifies that the test results contain the correct links to source code files. So the issue you are having puzzles me.
Would it be possible for you to share a project with me where you experience this issue? Maybe as a pull request to `TestProjects`. That would be appreciated, so I can reproduce this issue.

**Comment by zacharybussey** [comment]
I've just updated to the latest version of the plugin.  Everything seems to be working correctly now with the PhantomJS browser, so I'll close this issue.

**Comment by MortenHoustonLudvigsen** [comment]
That sounds great! Thanks.
