### ISSUE TITLE
"URI formats are not supported"

### ISSUE THREAD

**Issue by dam0** [MortenHoustonLudvigsen/KarmaTestAdapter#5]
Using VS2015 Preview...

After awhile I had the Test Explorer showing the tests, but not today unfortunately.
Displays "URI formats are not supported" in the Tests output window. Could this be a path issue?
Then why was it previously working for me? Sorry can't be of more help..

**Comment by MortenHoustonLudvigsen** [comment]
I will be concentrating on #9, which I hope will solve other issues.
