### ISSUE TITLE
JSON settings example

### ISSUE THREAD

**Issue by TomBecker-BD** [MortenHoustonLudvigsen/KarmaTestAdapter#7]
The JSON settings example has: "karmaConfigFile": "karma.conf.test.js",
The initial 'k' should be capitalized ("KarmaConfigFile") to conform to the schema. 

I would like to suggest setting the "LogDirectory" to "TestResults/Karma". VSTest creates "TestResults" directories and "TestResults" is in the VS default .gitignore file. Similarly "OutputDirectory" could be "TestResults/Karma/Output". 

My karma.conf.js is set up to run in 3 browsers (Chrome, FireFox and IE). I finally got it to work with Karma Test Adapter by overriding the config to use only Chrome. It seemed to be a problem with actually running the tests; no karma-vs-reporter.xml file was produced. But it worked fine running Karma from the command line. If there is a way you to get it to work, I would appreciate an example. If not, then maybe it is a separate issue.

**Comment by MortenHoustonLudvigsen** [comment]
I have changed the example as suggested. Thanks!
I will be concentrating on #9, which I hope will solve the other issues.

**Comment by TomBecker-BD** [comment]
Looks good, thanks!
